"relative line numbers
set number relativenumber
"toggle to absolute line numbers unless we are in normal focus
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

"hack from reddit to keep terminal windows in the buffer list
augroup custom_term
    autocmd!
    autocmd TermOpen * setlocal nonumber norelativenumber bufhidden=hide
augroup END

set t_AB=^[[48;5;%dm
set t_AF=^[[38;5;%dm
set t_Co=256
set termguicolors
set colorcolumn=80
set cursorline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='violet'
colorscheme inkpot

"Rainbow parentheses (kien version, not junegunn)
let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]
au VimEnter * RainbowParentheses

set mouse=a
let mapleader=" "
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
nnoremap <silent> <leader>q :lclose<bar>b#<bar>bd #<CR>

"set up vim-lsp (and asyncomplete)
nnoremap <silent> gd :LspDefinition<CR>
nnoremap <silent> gr :LspReferences<CR>
inoremap <expr> <Tab>    pumvisible() ? "\<C-y>" : "\<Tab>"
set completeopt+=preview
"intelephense is faster, better feature support
au User lsp_setup call lsp#register_server({
            \ 'name': 'intelephense',
            \ 'cmd': {server_info->['intelephense','--stdio']},
            \ 'whitelist': ['php'],
            \ })
"psalm is better at finding errors
au User lsp_setup call lsp#register_server({
            \ 'name': 'psalm',
            \ 'cmd': {server_info->['php','vendor/bin/psalm-language-server']},
            \ 'whitelist': ['php'],
            \ })
let g:lsp_signs_enabled = 1
let g:lsp_signs_error = {'text': '✗'}
let g:lsp_signs_warning = {'text': '!!'}
let g:lsp_signs_hint = {'text': '!'}
let g:lsp_diagnostics_echo_cursor = 1

"vista (companion to vim-lsp)
let g:vista_default_executive = 'vim_lsp'

"set up fzf (fuzzy finder)
nmap <Leader>F :Files<CR>
nmap <Leader>a :Ag<Space>
nmap <Leader>b :Buffers<CR>
nmap <Leader>f :GFiles<CR>

"slime
let g:slime_target = "neovim"

" Vdebug
let g:vdebug_keymap = {
\    "run" : "<Leader>/",
\    "run_to_cursor" : "<Up>",
\    "step_over" : "<Down>",
\    "step_into" : "<Right>",
\    "step_out" : "<Left>",
\    "close" : "q",
\    "detach" : "x",
\    "set_breakpoint" : "<Leader>p",
\    "eval_visual" : "<Leader>e"
\}

"nerdtree autoload (this seems annoying)
"autocmd vimenter * NERDTree

autocmd BufRead,BufNewFile *.elm set filetype=elm
autocmd FileType elm :packadd elm-vim
autocmd FileType jsonnet :packadd vim-jsonnet

